"""
Alembic 자동 생성 마이그레이션 스크립트 템플릿
- 이 파일은 'alembic revision --autogenerate' 실행 시 기본 템플릿으로 사용됩니다.
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql  # PostgreSQL JSONB 등 사용

# revision identifiers, used by Alembic.
revision = 'd6802b63c966'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    """스키마 업그레이드 적용"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_backups_database_id_created_at', 'backups', ['database_id', 'created_at'], unique=False)
    op.create_index('ix_backups_status_created_at', 'backups', ['status', 'created_at'], unique=False)
    op.create_index('ix_schedules_active_next_run', 'schedules', ['is_active', 'next_run'], unique=False)
    op.alter_column(
        'system_logs',
        'details',
        existing_type=sa.TEXT(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        postgresql_using='details::jsonb'  # PostgreSQL 타입 변경 시 USING 절 필요
    )
    op.create_index('ix_system_logs_details_gin', 'system_logs', ['details'], unique=False, postgresql_using='gin')
    op.create_index('ix_system_logs_level_component_created_at', 'system_logs', ['level', 'component', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """스키마 다운그레이드 적용(롤백)"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_system_logs_level_component_created_at', table_name='system_logs')
    op.drop_index('ix_system_logs_details_gin', table_name='system_logs', postgresql_using='gin')
    op.alter_column(
        'system_logs',
        'details',
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.TEXT(),
        existing_nullable=True,
        postgresql_using='details::text'  # JSONB -> TEXT 복구 시 USING 절 필요
    )
    op.drop_index('ix_schedules_active_next_run', table_name='schedules')
    op.drop_index('ix_backups_status_created_at', table_name='backups')
    op.drop_index('ix_backups_database_id_created_at', table_name='backups')
    # ### end Alembic commands ###
